DROP TABLE IF EXISTS APPOINTMENT;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PACKAGE;
DROP TABLE IF EXISTS TRAINER;


CREATE TABLE PACKAGE(
	PACKAGE_ID INT PRIMARY KEY,
    PACKAGE_NAME VARCHAR(50),
    SESSION_PER_WEEK TINYINT UNSIGNED,
    PRICE_PER_SESSION FLOAT(5,2)
);

INSERT INTO PACKAGE VALUES
(1,"One Time Appointment",null,500),
(2,"4 Session per week",4,400),
(3,"5 Session per week",5,300);

CREATE TABLE TRAINER(
	TRAINER_ID INT PRIMARY KEY,
    TRAINER_GENDER VARCHAR(50)
);
INSERT INTO TRAINER VALUES
(1,"MALE"),
(2,"FEMALE");

CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBER BIGINT NOT NULL,
    DOB DATE NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    ADDRESS_LINE_1 VARCHAR(50) NOT NULL,
    ADDRESS_LINE_2 VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    PIN_CODE MEDIUMINT UNSIGNED NOT NULL
);

INSERT INTO USERS VALUES
(1,"RUTHVIK",1234567890,'1999-12-31',"RUTHVIKVACHHANI718@GMAIL.COM","A/9,G-3,Vlamiki C.H.S","YASHASVI NAGAR,DHOKALI ROAD","THANE","MAHARASHTRA","INDIA",400601),
(2,"LUFFY",1234567891,'1999-11-30',"RUTHVIKVACHHANI01@GMAIL.COM","A/9,G-3,Vlamiki C.H.S","YASHASVI NAGAR,DHOKALI ROAD","RAJKOT","GUJRAT","INDIA",400602);

CREATE TABLE APPOINTMENT(
	APPOINTMENT_ID INT PRIMARY KEY,
    USER_ID INT,
    PACKAGE_ID INT,
    TRAINER_ID INT,
    PHYSIOTHERAPIST_REQUIREMENTS BOOLEAN,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY(PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID),
    FOREIGN KEY(TRAINER_ID) REFERENCES TRAINER(TRAINER_ID)
);

INSERT INTO APPOINTMENT VALUES
(1,1,1,1,FALSE),
(2,1,2,2,TRUE),
(3,2,3,NULL,FALSE);

